[package]
name = "bib_sort"
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"

[dependencies]
regex = "1.11.1"
clap = {version = "^4.5.36", features=["derive", "cargo", "color", "help"]}
lazy_static = "1.5.0"


[profile.release]
lto = true
strip = true
